spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/isaciBolsasAPI
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
